### ISSUE TITLE
Problem with fork executions and pipe handling

### ISSUE THREAD

**Issue by Pastequee** [Arthur-PI/42_minishell#23]
There is two things to know with pipes, when you do `pipe(fd)` it gives you `fd[0]` to read and `fd[1]` to write, its like a tunnel with 2 ends, and the point with execution flow is that if you try to let say write from a pipe like `write(fd[1], "Hello", 5)` and that the other end of the pipe `fd[0]` have been closed like this `close(fd[0])` then the process that tried to write to the pipe automatically receive a `SIGPIPE` signal and terminate. This is why you don't have to kill all your processes once the last one is finished, they should stop on their own. If you manage your pipes open/close this should be done on its own.

Example of command:
`cat /dev/random | head`
In this case, `head` will read 10 lines and then terminate, which will close its reading end of the pipe and when `cat` will try to write to the pipe he will therefore receive a `SIGPIPE` and terminate.
So the whole `killing_processes()` function should not exist.
(If not clear ASK (really))

**Comment by pteaaa** [comment]
je réponds en français pcq c trop dur sinon. J'ai l'impression d'avoir compris ce que t'as dit et en vrai avant que je crée le killing_processes, le cat /dev/random | head fonctionnait. 
juste j'ai fait le test cat | cat | ls et la l'ordi bug 
C'est un probleme que j'arrive pas à régler, donc si toi t'as compris qqchose qui allait pas dans mon code ou autre, je veux bien que tu me réexpliques stp :/

**Comment by Pastequee** [comment]
Ouais desole, euh alors ok je vois ce que tu veux dire mais en fait je pense que ca fonctionnait mais t'avais l'impression que ca buguait (enfin je pense faut verifier)  
Mais du coup pour etre clair la commande `cat | cat | cat | ls` est bloque et tu dois faire 3 fois entrer pour que ca quitte (dans bash en tout cas), mais du coup pourquoi ? Pourquoi ca quitte pas juste direct si `ls` s'arrete direct ?  
Et bah en fait ce qu'il se passe c'est que `cat` sans argument attend en lecture sur stdin que l'utilisateur donne du texte AVANT d'essayer d'ecrire sur le pipe (qui va le kill) et du coup le deroulelement c'est:  
- 1er enter: le `1er cat` donne enter au `2eme cat`, le `2eme cat` donne enter au `3eme cat`, le 3eme cat essaye d'ecrire dans le pipe de `ls` qui existe plus et meurt par `SIGPIPE`, sauf que la, le `1er cat` et le `2eme cat` reparte en attente de texte pcq ils sont pas mort
- 2eme enter: le `1er cat` donne enter au `2eme cat`, le `2eme cat` essaye d'ecrire dans le pipe du `3eme cat` qui est deja mort donc recoit `SIGPIPE`, le `1er cat` est repartit en attente de texte.  
- 3eme enter: le `1er cat` essaye d'ecrire dans le pipe du `2eme cat` qui est mort et donc recoit a son tour `SIGPIPE` et meurt, voila c'est termine

J'espere que c'est clair, du coup c'est ca le deroule normal de cette commande et si les pipe sont bien gere et ferme au bon moment ca devrait fonctionner sans kill, et d'ailleur normalement ya aucun cas on tu devrais avoir besoin de kill 😃
